/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type ForwardedCall struct {
	Id int32 `json:"id"`
	CallTime time.Time `json:"callTime"`
	Caller string `json:"caller"`
	// Inbound id
	Via string `json:"via"`
	Receiver string `json:"receiver"`
}
