/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type InviteSubaccountInputObject struct {
	// Invitation email will be sent to this email address.
	Email string `json:"email"`
	// Type of account: *   **A** for Administrator sub-account *   **U** for Regular User 
	Role string `json:"role"`
}
