/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type Conversation struct {
	Id int32 `json:"id"`
	Direction string `json:"direction"`
	Sender string `json:"sender"`
	MessageTime time.Time `json:"messageTime"`
	Text string `json:"text"`
	Receiver string `json:"receiver"`
	Status string `json:"status"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	SessionId int32 `json:"sessionId"`
}
