/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type MessagesIcs struct {
	Id int32 `json:"id"`
	NextSend time.Time `json:"nextSend"`
	Rrule string `json:"rrule"`
	Session *MessageSession `json:"session"`
	LastSent time.Time `json:"lastSent"`
	ContactName string `json:"contactName"`
	Parameters *MessagesIcsParameters `json:"parameters"`
	Type_ string `json:"type"`
	Summary string `json:"summary"`
	TextParameters *MessagesIcsTextParameters `json:"textParameters"`
	FirstOccurrence time.Time `json:"firstOccurrence"`
	LastOccurrence time.Time `json:"lastOccurrence"`
	RecipientsCount int32 `json:"recipientsCount"`
	Timezone string `json:"timezone"`
	Completed bool `json:"completed"`
	Avatar string `json:"avatar"`
	CreatedAt time.Time `json:"createdAt"`
}
