/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type SurveySenderCountries struct {
	Id int32 `json:"id"`
	CountryName string `json:"countryName"`
	FromNumber string `json:"fromNumber"`
	AllowDedicated bool `json:"allowDedicated"`
}
