/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type UnsubscribedContact struct {
	Id int32 `json:"id"`
	Phone string `json:"phone"`
	UnsubscribeTime time.Time `json:"unsubscribeTime"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
}
