/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type CreatePushTokenInputObject struct {
	// Device ID for push notification service
	DeviceId string `json:"deviceId"`
	// Push notification service type: a for Apple Push Notifications, g for Google Cloud Messaging
	PushServiceType string `json:"pushServiceType"`
}
