/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type Contact struct {
	// Contact ID.
	Id int32 `json:"id"`
	Favorited bool `json:"favorited"`
	Blocked bool `json:"blocked"`
	// Contact first name.
	FirstName string `json:"firstName"`
	// Contact last name.
	LastName string `json:"lastName"`
	// Company name.
	CompanyName string `json:"companyName"`
	// Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
	Phone string `json:"phone"`
	// Contact email address.
	Email string `json:"email"`
	// Contact country.
	Country *Country `json:"country"`
	// See [Custom Fields](http://docs.textmagictesting.com/tag#Custom-Fields) section.
	CustomFields []ContactCustomField `json:"customFields"`
	User *User `json:"user"`
	Lists []List `json:"lists"`
	PhoneType string `json:"phoneType"`
	Avatar *ContactImage `json:"avatar"`
	Notes []ContactNote `json:"notes"`
}
