/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type GetMessageSessionStatResponse struct {
	Failed int32 `json:"failed"`
	Delivered int32 `json:"delivered"`
	Accepted int32 `json:"accepted"`
	Rejected int32 `json:"rejected"`
	Scheduled int32 `json:"scheduled"`
	All int32 `json:"all"`
	Sent int32 `json:"sent"`
}
