/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type GetMessagingCountersResponse struct {
	// Total contacts amount.
	Contacts int32 `json:"contacts"`
	// Total sent messages amount.
	Sent int32 `json:"sent"`
	// Total received messages amount.
	Received int32 `json:"received"`
}
