/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type MessagingStatItem struct {
	ReplyRate float32 `json:"replyRate"`
	Date time.Time `json:"date"`
	DeliveryRate float32 `json:"deliveryRate"`
	Costs float32 `json:"costs"`
	MessagesReceived int32 `json:"messagesReceived"`
	MessagesSentDelivered int32 `json:"messagesSentDelivered"`
	MessagesSentAccepted int32 `json:"messagesSentAccepted"`
	MessagesSentBuffered int32 `json:"messagesSentBuffered"`
	MessagesSentFailed int32 `json:"messagesSentFailed"`
	MessagesSentRejected int32 `json:"messagesSentRejected"`
	MessagesSentParts int32 `json:"messagesSentParts"`
}
