/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type MuteChatsBulkInputObject struct {
	// Entity ID(s), separated by comma
	Ids string `json:"ids,omitempty"`
	// Entity ID(s), separated by comma
	All bool `json:"all,omitempty"`
	// Mute for N hours
	For_ int32 `json:"for,omitempty"`
}
