/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type DoAuthInputObject struct {
	// Account username or email
	Username string `json:"username"`
	// Account password
	Password string `json:"password"`
	// Application name
	AppName string `json:"appName,omitempty"`
	// Application version
	AppVersion string `json:"appVersion,omitempty"`
	// Device ID for push notification service
	DeviceId string `json:"deviceId,omitempty"`
	// required when deviceId provided. Push notification service type: a for Apple Push Notifications, g for Google Cloud Messaging
	PushServiceType string `json:"pushServiceType,omitempty"`
	// required when 2FA enabled on account. 2FA challenge response (SMS code or security question answer)
	TfaCode string `json:"tfaCode,omitempty"`
	// required when 2FA enabled on account. 2FA challenge response (SMS code or security question answer)
	TfaId string `json:"tfaId,omitempty"`
}
