/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type GetMessagePriceResponse struct {
	Total float32 `json:"total"`
	Parts int32 `json:"parts"`
	Countries *interface{} `json:"countries"`
}
