/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type ImportColumnMappingItem struct {
	// Column position in file (indexed from 0)
	ColumnPositionInFile string `json:"columnPositionInFile"`
	// Field or custom field id
	FieldOrCustomFieldId string `json:"fieldOrCustomFieldId"`
}
