/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type SendMessageResponse struct {
	Id int32 `json:"id"`
	Href string `json:"href"`
	Type_ string `json:"type"`
	SessionId int32 `json:"sessionId"`
	BulkId int32 `json:"bulkId"`
	MessageId int32 `json:"messageId"`
	ScheduleId int32 `json:"scheduleId"`
	ChatId int32 `json:"chatId"`
}
