/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type UpdateCustomFieldValueInputObject struct {
	// [Contact](/docs/api/contacts/) 
	ContactId int32 `json:"contactId,omitempty"`
	// Custom field value. Note that this value is not parsed in any way. It is stored and used in tags exactly as you send it.
	Value string `json:"value,omitempty"`
}
