/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type UpdateContactInputObject struct {
	// Contact first name
	FirstName string `json:"firstName,omitempty"`
	// Contact last name
	LastName string `json:"lastName,omitempty"`
	// Contact phone number in E.164 (international) format without leading + or zeroes
	Phone string `json:"phone"`
	// Contact email
	Email string `json:"email,omitempty"`
	// Contact company name
	CompanyName string `json:"companyName,omitempty"`
	// Array of list resources id contact will be assigned to
	Lists string `json:"lists"`
	// Is contact favorited
	Favorited bool `json:"favorited,omitempty"`
	// Is contact blocked for outgoing and incoming messaging
	Blocked bool `json:"blocked,omitempty"`
	// Force type of phone. Possible values: 0 - landline, 1 - mobile. Default is -1 (auto detection)
	Type_ int32 `json:"type,omitempty"`
	CustomFieldValues *interface{} `json:"customFieldValues,omitempty"`
	// Treat phone number passed in request body as local
	Local int32 `json:"local,omitempty"`
	// 2-letter ISO country code for local phone numbers, used when local is  set to true. Default is account country
	Country string `json:"country,omitempty"`
}
