/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type Invoice struct {
	Id int32 `json:"id"`
	Bundle int32 `json:"bundle"`
	Currency string `json:"currency"`
	Vat float32 `json:"vat"`
	PaymentMethod string `json:"paymentMethod"`
}
