/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type Contact struct {
	Id int32 `json:"id"`
	Favorited bool `json:"favorited"`
	Blocked bool `json:"blocked"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	CompanyName string `json:"companyName"`
	Phone string `json:"phone"`
	Email string `json:"email"`
	Country *Country `json:"country"`
	CustomFields []ContactCustomField `json:"customFields"`
	User *User `json:"user"`
	Lists []List `json:"lists"`
	PhoneType string `json:"phoneType"`
	Avatar *ContactImage `json:"avatar"`
	Notes []ContactNote `json:"notes"`
}
