/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type SenderId struct {
	Id int32 `json:"id"`
	SenderId string `json:"senderId"`
	User *User `json:"user"`
	// A - accepted, R - rejected, P - pending
	Status string `json:"status"`
}
