/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type CreateSurveyNodeInputObject struct {
	// Node type. \\'a\\' answer; \\'q\\' - question
	NodeType string `json:"nodeType,omitempty"`
	// Node label
	Label string `json:"label,omitempty"`
	// Node body
	Body string `json:"body,omitempty"`
	// Start node id
	StartNode int32 `json:"startNode,omitempty"`
	// Define delay for sending question to recipients after previous answer.
	SendDelay int32 `json:"sendDelay,omitempty"`
}
