/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type ContactNote struct {
	Id int32 `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	Note string `json:"note"`
	User *User `json:"user"`
}
