/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type MessageOut struct {
	Id int32 `json:"id"`
	ContactId int32 `json:"contactId"`
	SessionId int32 `json:"sessionId"`
	Receiver string `json:"receiver,omitempty"`
	MessageTime time.Time `json:"messageTime"`
	// q - queued s - scheduled queue e - sending error r - enroute a - acked d - delivered b - buffered f - failed u - unknown j - rejected i - bulk insert p - scheduled suspend h - queue suspend
	Status string `json:"status"`
	Avatar string `json:"avatar"`
	Text string `json:"text"`
	Deleted bool `json:"deleted,omitempty"`
	Charset string `json:"charset"`
	CharsetLabel string `json:"charsetLabel"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	Country string `json:"country"`
	Sender string `json:"sender,omitempty"`
	Phone string `json:"phone,omitempty"`
	Price float32 `json:"price,omitempty"`
	PartsCount int32 `json:"partsCount"`
	FromEmail string `json:"fromEmail,omitempty"`
	FromNumber string `json:"fromNumber,omitempty"`
	SmscId string `json:"smscId,omitempty"`
	Contact string `json:"contact,omitempty"`
	Source string `json:"source,omitempty"`
	DeliveredCount int32 `json:"deliveredCount,omitempty"`
	NumbersCount int32 `json:"numbersCount,omitempty"`
	UserId int32 `json:"userId,omitempty"`
	CreditsPrice string `json:"creditsPrice,omitempty"`
	Chars int32 `json:"chars,omitempty"`
}
