/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type GetContactsAutocompleteResponseItem struct {
	// Id of entity. 0 if object is a Reply
	EntityId int32 `json:"entityId"`
	// 
	EntityType string `json:"entityType"`
	// Id of contact/list if entityType is contact/list OR phone number if entityType is reply
	Value string `json:"value"`
	// Name of the contact/list if entityType is contact/list OR phone number if entityType is reply
	Label string `json:"label"`
	// If contact or list was shared by another user then name if this user will be shown
	SharedBy string `json:"sharedBy"`
	Avatar string `json:"avatar"`
	// If contact was marked as favourited
	Favorited bool `json:"favorited"`
	// Owner id of the contact/list (if it was shared)
	UserId int32 `json:"userId"`
	CountryName string `json:"countryName"`
	Qposition int32 `json:"qposition"`
	Rposition int32 `json:"rposition"`
}
