/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type MessageSession struct {
	Id int32 `json:"id"`
	StartTime string `json:"startTime"`
	Text string `json:"text"`
	Source string `json:"source"`
	ReferenceId string `json:"referenceId"`
	Price float32 `json:"price"`
	NumbersCount int32 `json:"numbersCount"`
	Destination string `json:"destination"`
}
