/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

// Returned when the form has errors
type BadRequestResponse struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
	Errors *BadRequestResponseErrors `json:"errors,omitempty"`
}
