/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type UpdateCurrentUserInputObject struct {
	Username string `json:"username,omitempty"`
	// Account first name.
	FirstName string `json:"firstName,omitempty"`
	// Account last name.
	LastName string `json:"lastName,omitempty"`
	Email string `json:"email,omitempty"`
	Phone string `json:"phone,omitempty"`
	// Account company name.
	Company string `json:"company,omitempty"`
	// The timezome internal id
	Timezone int32 `json:"timezone,omitempty"`
}
