/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type MessageIn struct {
	Id int32 `json:"id"`
	Sender string `json:"sender"`
	Receiver string `json:"receiver"`
	MessageTime time.Time `json:"messageTime"`
	Text string `json:"text"`
	ContactId int32 `json:"contactId,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	Avatar string `json:"avatar"`
}
