/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type GetSubaccountsWithTokensInputObject struct {
	// Application name
	AppName string `json:"appName"`
	// Your account password
	Password string `json:"password"`
}
