/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type User struct {
	Id int32 `json:"id"`
	Username string `json:"username"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	Email string `json:"email"`
	Status string `json:"status"`
	Balance float32 `json:"balance"`
	Phone string `json:"phone"`
	Company string `json:"company"`
	Currency *Currency `json:"currency"`
	Country *Country `json:"country"`
	Timezone *Timezone `json:"timezone"`
	SubaccountType string `json:"subaccountType"`
	EmailAccepted bool `json:"emailAccepted"`
	PhoneAccepted bool `json:"phoneAccepted"`
	Avatar *UserImage `json:"avatar"`
}
