/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type Currency struct {
	Id string `json:"id"`
	UnicodeSymbol string `json:"unicodeSymbol"`
	HtmlSymbol string `json:"htmlSymbol"`
}
