/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type DoAuthResponse struct {
	Username string `json:"username"`
	Token string `json:"token"`
	Expires time.Time `json:"expires"`
	MinVersions *DoAuthResponseMinVersions `json:"minVersions"`
	DisallowedRules []string `json:"disallowedRules"`
}
