/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type DoAuthResponseMinVersions struct {
	Ios int32 `json:"ios"`
	Android int32 `json:"android"`
	Desktop int32 `json:"desktop"`
}
