/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type DoCarrierLookupResponse struct {
	Cost float32 `json:"cost"`
	Country *Country `json:"country,omitempty"`
	Local string `json:"local"`
	Type_ string `json:"type"`
	Carrier string `json:"carrier"`
	Number164 string `json:"number164"`
	Valid bool `json:"valid"`
}
