/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type CreateListInputObject struct {
	// List name.
	Name string `json:"name"`
	// Should new list be shared among all the sub-accounts? The default is 0 (false).
	Shared bool `json:"shared,omitempty"`
	// Is list favorited. Default is false.
	Favorited bool `json:"favorited,omitempty"`
	// Is list default for new contacts (web only). Default is false.
	IsDefault bool `json:"isDefault,omitempty"`
}
