/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type GetOutboundMessagesHistoryResponse struct {
	LastId int32 `json:"lastId"`
	NextLastId int32 `json:"nextLastId"`
	Limit int32 `json:"limit"`
	Resources []MessageOut `json:"resources"`
}
