/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type UpdateSurveyNodeInputObject struct {
	// Node label
	Label string `json:"label,omitempty"`
	// Define node is ending for survey. Default is false
	IsEndNode bool `json:"isEndNode,omitempty"`
	// Node body
	Body string `json:"body,omitempty"`
	// Define delay for sending question to recipients after previous answer.
	SendDelay int32 `json:"sendDelay,omitempty"`
}
