/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type GetAvailableDedicatedNumbersResponse struct {
	// Array of phone number strings.
	Numbers []string `json:"numbers"`
	// Dedicated number monthly fee for this country. Returned in current [account](/docs/api/account/) currency.@TODO
	Price float32 `json:"price"`
}
