/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type BuyDedicatedNumberInputObject struct {
	// Desired dedicated phone number in international E.164 format
	Phone string `json:"phone"`
	// Dedicated number country. Two charactes in upper case.
	Country string `json:"country"`
	// User ID this number will be assigned to
	UserId int32 `json:"userId"`
}
