/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type MessageIn struct {
	// The ID of the inbound message.
	Id int32 `json:"id"`
	// The sender’s phone number.
	Sender string `json:"sender"`
	// The receiver’s phone number (i.e. your dedicated or shared reply number).
	Receiver string `json:"receiver"`
	// The time when the message reached the TextMagic API endpoint.
	MessageTime time.Time `json:"messageTime"`
	// The text from the received message.
	Text string `json:"text"`
	ContactId int32 `json:"contactId,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	Avatar string `json:"avatar"`
}
