/*
 * TextMagic API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Contact: support@textmagi.biz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type MergeSurveyNodesInputObject struct {
	// First node id
	FirstNode int32 `json:"firstNode"`
	// Second node id
	SecondNode int32 `json:"secondNode"`
}
